apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
 name: litserve-runtime
 annotations:
   openshift.io/display-name: LitServe ServingRuntime for KServe
 labels:
   opendatahub.io/dashboard: "true"
spec:
 annotations:
   prometheus.io/port: "8080"
   prometheus.io/path: /metrics
 multiModel: false
 supportedModelFormats:
   - autoSelect: true
     name: xgboost
     priority: 2
     version: "1"
 containers:
   - name: kserve-container
     image: quay.io/rh-ee-equarmjn/litserve-xgboost-image
     command:
       - python
       - server.py
     args:
       - --model=/mnt/models
       - --http_port=8080
       - --served-model-name={{.Name}}
     ports:
       - containerPort: 8080
         protocol: TCP
     resources:
       limits:
         cpu: "1"
         memory: 2Gi
       requests:
         cpu: "1"
         memory: 2Gi